### ISSUE TITLE
vertx maven archetype has no integration tests template for clojure

### ISSUE THREAD

**Issue by jianglibo** [vert-x/mod-lang-clojure#125]
so I copy one from source APIIntegrationTests.java. put it in integration/clojure/ClojureScriptIntegrationTest.java, when I run mvn intergration-test, It display "Started clojure verticle: basic_integration_test.clj" and stalled. the content of basic_integration_test.clj is copy from source net_test.clj.

what's wrong?

**Comment by tobias** [comment]
There are two types of tests in mod-lang-clojure - some that use clojure.test, and others that use vertx.testtools instead. `APIIntegrationTests` can only load and run testtool-style tests (like the ones under `lang-module/src/test/resources/`. The tests under `api/src/test/clojure/` are designed to be ran directly in clojure, which is handled by the

**Comment by jianglibo** [comment]
I see. thank you very much. help me a lot.
