### ISSUE TITLE
using vertx from repl

### ISSUE THREAD

**Issue by cocodrino** [vert-x/mod-lang-clojure#127]
Hi.. it's possible run vertx from the repl, I'm using https://github.com/isaiah/lein-vertx for generate the vertx project and I found this

http://vertx.io/api/clojure/vertx.repl.html

but it's not completely clear to me how use it...basically I need run http client and get the response (I don't need deploy verticles)...I suppose than I need add a few jars to my classpath before no?

**Comment by tobias** [comment]
`vertx.repl` is used when you want repl access within a traditional verticle setup. If you want to use Vert.x embedded, without deploying a verticle, you don't need that namespace. You also don't need lein-vertx - you can start up a Vert.x instance from a regular clojure application. See https://github.com/tobias/vertx-sample-benchmark-app as an example of doing that.

**Comment by cocodrino** [comment]
thanks tobias, that is exactly what I was looking for...
