### ISSUE TITLE
possible error in docs for vertx 2.x ? put-header/add-header ...

### ISSUE THREAD

**Issue by cocodrino** [vert-x/mod-lang-clojure#128]
Hi guys, in the doc http://vertx.io/core_manual_clojure.html#request-headers

appears

```clojure
(-> (http/server)
    (http/on-request
      #(-> %
           (http/server-response)
           (http/put-header "Content-Type" "text/plain")
           (http/end (pr-str (http/headers %)))))
    (http/listen 8080)
```

I can't find the put-header method, I think than would be add-header instead...it's not a big deal, but yep, it's a bit annoying :D ....

**Comment by tobias** [comment]
Thanks! PR sent to vertx.io: https://github.com/vert-x/vert-x.github.io/pull/57
