### ISSUE TITLE
which route use as argument in deploy-verticle function when I use lein vertx

### ISSUE THREAD

**Issue by cocodrino** [vert-x/mod-lang-clojure#131]
Hi, in the documentation says

     Where main is the name of the Verticle (i.e. the name of the script or FQCN of the class).

this works for me in scala
```scala
container.simpleDeploy("scala:com.example.TitanDB", numberVerticles = 5)
```

but I try do the same in my clojure project and always fails:

```clojure
(vertx/deploy-verticle "clojure:proj2.httpclientj" :instances 10) ;;proj2 is my proj name...all clojure files
are inside src/cloj2 folder

(vertx/deploy-verticle "clojure:httpclientj.clj" :instances 10) ;;fails!
(vertx/deploy-verticle "httpclientj.clj" :instances 10) ;;fails!
(vertx/deploy-verticle "clojure:proj2.httpclientj" :instances 10) ;;fails!
(vertx/deploy-verticle "clojure:httpclientj" :instances 10) ;;fails!
(vertx/deploy-verticle "proj2.httpclient" :instances 10) ;;fails!
```

basically I've used all availables alternatives except the correct one..can you tell me which is the correct way :D ..I'm using lein vertx project.

**Comment by tobias** [comment]
If `httpclientj.clj` is at `src/proj2/httpclientj.clj`, then `(vertx/deploy-verticle "proj2/httpclientj.clj" :instances 10)` should work. Let me know if it doesn't.

**Comment by cocodrino** [comment]
thanks tobias, it was exactly the only option than I didnt try :D...I'm getting an error

        Wrong number of args (2) passed to: buffer/def-get, compiling:(buffer.clj:150:1)

but checking *"cannot deploy multiple instances for one verticle programly from clojure verticle #130"* seems fixed in the new vertx clojure release, I'll try it or use the @jianglibo trick.

**Comment by tobias** [comment]
Good deal. Give that SNAPSHOT release a try and comment on #130 if it works for you. I'll try to get it in a real release soon.
