### ISSUE TITLE
ClojureVerticleFactory should serialize verticle start()

### ISSUE THREAD

**Issue by tobias** [vert-x/mod-lang-clojure#134]
If clojure.jar is on the classpath, verticles don't get isolated runtimes, which isn't really a problem in itself, but does cause issues with namespaces being accessed before they are completely loaded. Serializing start() should prevent that.

**Comment by tobias** [comment]
I now realize this is also an issue even when you don't have a clojure.jar on the classpath, since multiple instances of the same verticle will share the same runtime, and may collide loading namespaces there as well.

**Comment by prio** [comment]
Hi Toby. Have been testing this since last Friday and my application is behaving much better, no longer seeing the errors I was previously seeing when restarting.

**Comment by tobias** [comment]
@prio - thanks for the feedback! This has been released in v1.0.5 if you want to move past the SNAPSHOT.
